### ISSUE TITLE
Support for 70mai A500S+ (and other similar)?

### ISSUE THREAD

**Issue by danielszilagyi** [XuZhen86/70MaiM300Toolbox#1]
Hi,

First of all thank you for your efforts on creating this tool. I have a 70mai A500S+ smart dash cam, and I am also bugged by the app/the limitations brought by the design of the wireless connectivity options.

I was able to retrieve the token using your guidelines and I can retrieve the SD card status.
On my device with the latest firmware, telnet and ftp are open by the way, with user root and no password, found out [here](https://dashcamtalk.com/forum/threads/a500s-preliminary-hacking.46763/)

Basically sd card information and start/stop recording works but get-files runs into some delimiter error - probably the API has a bit of different calls?

```text
I0402 20:00:24.633797 140642188491592 connectionpool.py:228] Starting new HTTP connection (1): 192.168.0.1:80
I0402 20:00:24.915383 140642188491592 connectionpool.py:456] http://192.168.0.1:80 "GET /cgi-bin/getfilecount.cgi?-timestamp=1680458424&-signkey=cc332a6eb5ceaf55de4854d2a16e317c HTTP/1.1" 200 None
I0402 20:00:24.916453 140642188491592 httputil.py:51] response.text = {"ResultCode":"0","Result":[{"type":"0","count":"304"},{"type":"1","count":"5"},{"type":"2","count":"0"},{"type":"3","count":"5"},{"type":"4","count":"150"},{"type":"5","count":"0"},{"type":"6","count":"4"},{"type":"7","count":"0"},{"type":"8","count":"140"},{"type":"9","count":"0"}]}

json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 283 (char 282)
```

Do you think it would be much effort to make your cli work with this camera as well?

thanks,
Daniel

**Comment by danielszilagyi** [comment]
Adding some input from the packet capture while trying to use all functions in the app:
Bootmusic would be especially nice if you could help me try set to 0, since this cannot be done from the app or the device and a bit of annoying even with lowest volume.

```text
GET /cgi-bin/getdeviceattr.cgi?&-timestamp=1680458830&-signkey=fb447d752075702268d7273e98780049 HTTP/1.1
_os_: Android
_ver_: 3.3.0
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Sun, 02 Apr 2023 12:07:49 GMT
Last-Modified: Sun, 02 Apr 2023 12:07:49 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"0","Result":{"name":"DR2500","softversion":"1.1.20ww","softversion_date":"2022.07.18","devchannel":"41002001","devts":"20230402200749","guidemode":"0","gpsdataversion":"1"}}



GET /cgi-bin/getAllMenu.cgi?&-timestamp=1680458827&-signkey=8a3d8918d02ff54a76460ba89c225c9f HTTP/1.1
_os_: Android
_ver_: 3.3.0
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Sun, 02 Apr 2023 12:07:46 GMT
Last-Modified: Sun, 02 Apr 2023 12:07:46 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"0","Result":{"audioin_mute":"0","volume":"3","splittime":"120","systime":"20230402200746","wifibootenable":"1","bootmusic":"1","videoencode":"hevc","resolution":"2592x1944P30","video_format":{"front":{"hevc":["2592x1944P30","2560x1920P30","1920x1440P30"],"h264":["1920x1440P30"]}},"voicecontrolenable":"1","collision_level":"3","Parking_on":"1","Parking_threshold":"3","Parking_entertime":"0","adas_on":"0","adas_limber_launch":"1","adas_lane_departure":"1","adas_limber_crash":"1","adas_environment_lable":"0","lapserec_on":"0","wdr_enable":"1","watermark_on":"1","speed_unit":"0","logoshowenable":"0","language_default":"English","language_support":["English","..............",".........",".........","Espa..ol","Portugu..s","............","Polski","....................."],"P1N0enable":"1","screenautosleep_time":"0","dateformat":"0","support_device_log":"1"}}

GET /cgi-bin/getwifi.cgi?&-timestamp=1680458833&-signkey=b9a4623a424b8e3d57eb51451f016471 HTTP/1.1
_os_: Android
_ver_: 3.3.0
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Sun, 02 Apr 2023 12:07:52 GMT
Last-Modified: Sun, 02 Apr 2023 12:07:52 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"0","Result":{"enablewifi":"1","wifissid":"70mai_Pro Plus+_bad3","secretmode":"3","whichkey":"0","wifikey":"29833730","linkstatus":"1"}}
```

Setting the video quality to high (smaller size) compression mode

```text
GET /cgi-bin/setparameter.cgi?&-workmode=0&-type=0&-value=1920x1440P30&-videoencode=h264&-timestamp=1680458839&-signkey=e2a50c6d2aee16a6acc0eb273d4b1cf2 HTTP/1.1
_os_: Android
_ver_: 3.3.0
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Sun, 02 Apr 2023 12:07:58 GMT
Last-Modified: Sun, 02 Apr 2023 12:07:58 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"0"}

GET /cgi-bin/getparameter.cgi?&-workmode=0&-type=0&-timestamp=1680458842&-signkey=52aa62b30bd388afc482b10bba1ef19b HTTP/1.1
_os_: Android
_ver_: 3.3.0
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Sun, 02 Apr 2023 12:08:01 GMT
Last-Modified: Sun, 02 Apr 2023 12:08:01 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"0","Result":{"resolution":"1920x1440P30"}}
```

Setting the video quality back

```text
GET /cgi-bin/setparameter.cgi?&-workmode=0&-type=0&-value=2592x1944P30&-videoencode=hevc&-timestamp=1680458849&-signkey=c2768d50978cde34b6aeb08876c6dac8 HTTP/1.1
_os_: Android
_ver_: 3.3.0
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Sun, 02 Apr 2023 12:08:08 GMT
Last-Modified: Sun, 02 Apr 2023 12:08:08 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"0"}

GET /cgi-bin/getparameter.cgi?&-workmode=0&-type=0&-timestamp=1680458852&-signkey=726bc477e48c1d34c4bd8f6ed70d9eed HTTP/1.1
_os_: Android
_ver_: 3.3.0
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Sun, 02 Apr 2023 12:08:11 GMT
Last-Modified: Sun, 02 Apr 2023 12:08:11 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"0","Result":{"resolution":"2592x1944P30"}}
```

Collision sensitivity

```text
GET /cgi-bin/setcollision.cgi?&-level=2&-timestamp=1680458869&-signkey=7ee327e4ac5bb26098b19ccb311c132d HTTP/1.1
_os_: Android
_ver_: 3.3.0
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Sun, 02 Apr 2023 12:08:28 GMT
Last-Modified: Sun, 02 Apr 2023 12:08:28 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"0"}
```

Always on settings

```text
GET /cgi-bin/getparkingwire.cgi?&-timestamp=1680458902&-signkey=30658df2e37493d2f68239c0de048612 HTTP/1.1
_os_: Android
_ver_: 3.3.0
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Sun, 02 Apr 2023 12:09:01 GMT
Last-Modified: Sun, 02 Apr 2023 12:09:01 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"0","Result":{"parkingwire":"1"}}
```

Parking collision sensitivity

```text
GET /cgi-bin/setparkingattr.cgi?&-threshold=1&-timestamp=1680458902&-signkey=a4dc9cbd6ddf3c6c0e46cd4f97c7b35f HTTP/1.1
_os_: Android
_ver_: 3.3.0
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Sun, 02 Apr 2023 12:09:01 GMT
Last-Modified: Sun, 02 Apr 2023 12:09:01 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"0"}
```

ADAS related settings

```text
GET /cgi-bin/getadasattr.cgi?&-timestamp=1680458918&-signkey=8edf4246c7f378da40fe983efe9cd168 HTTP/1.1
_os_: Android
_ver_: 3.3.0
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Sun, 02 Apr 2023 12:09:17 GMT
Last-Modified: Sun, 02 Apr 2023 12:09:17 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"0","Result":{"adas_on":"1","adas_limber_launch":"1","adas_lane_departure":"1","adas_limber_crash":"1","adas_environment_lable":"0"}}


GET /cgi-bin/setadasattr.cgi?&-adas_environment_lable=1&-timestamp=1680458922&-signkey=c7d4f53821b1cabb2c2fb0c49f18c33b HTTP/1.1
_os_: Android
_ver_: 3.3.0
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Sun, 02 Apr 2023 12:09:21 GMT
Last-Modified: Sun, 02 Apr 2023 12:09:21 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"0"}
```

get log from dvr

```
GET /cgi-bin/getdvrlog.cgi?&-timestamp=1680458933&-signkey=af104d2f83f42c013109027bdd71d8bd HTTP/1.1
_os_: Android
_ver_: 3.3.0
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Sun, 02 Apr 2023 12:09:33 GMT
Last-Modified: Sun, 02 Apr 2023 12:09:33 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"0","Result":{"file":"/usr/bin/log/log.tar.bz","size":"2669056"}}
```

no need to authenticate for plain gets, only the api calls, just retrieve `http://192.168.0.1/usr/bin/log/log.tar.bz`
less via telnet session also works on this path.
Wget of the files from sd card via http is not possible, although there is a symlink `sd` in /var/www but the files are being served by a `thttpd` complied in the camera app `main_app` and returns error 403 for these files. Transfer of the files is possible via FTP though.

**Comment by XuZhen86** [comment]
Hi Daniel, thanks for stopping by and leaving a comment! I'm dealing with a ton of stuff at the moment but I'll respond at the earliest convenience. 

For the `json.decoder.JSONDecodeError`, I suspect it's [this line](https://github.com/XuZhen86/70MaiM300Toolbox/blob/9f083e2c5dc2a8d9fefe4fc50f2fe73e186aae49/m300_toolbox/files/getfilecount.py#L8) causing the trouble. Judging from your log from `httputil.py:51`, the format looked good and doesn't need any fixing.
I think the fix would do something like: try parse the string, if it works, return success. If it doesn't work, try fix it and then parse it. If all fixes are exhausted, return error. 

At the same time, I noticed A500S+ has 9 types of file counts? I need to double check the logic related to [this](https://github.com/XuZhen86/70MaiM300Toolbox/blob/9f083e2c5dc2a8d9fefe4fc50f2fe73e186aae49/m300_toolbox/files/filetype.py#L5) to see if it's compatible with 9 types of file counts because it only lists 5. 
I think the command line arg could be improved to allow any number of types of files. 

For changing other settings, do you think it's useful to add a "Power User" mode, where the user could specify any cgi URL and args, and the tool would just call that URL with the timestamp and sign key. My rationale would be, with fixing the JSON parse error and adding support to unrestricted file types, this tool is no longer limited to M300. Adding a "Power User" mode opens up all the possibilities for customized interactions with many more camera models.

**Comment by danielszilagyi** [comment]
> Hi Daniel, thanks for stopping by and leaving a comment! I'm dealing with a ton of stuff at the moment but I'll respond at the earliest convenience.

Hi, thanks for getting back to me so quick, I also did some improvements in what I wanted to achieve with this car DVR.

> 
> For the `json.decoder.JSONDecodeError`, I suspect it's [this line](https://github.com/XuZhen86/70MaiM300Toolbox/blob/9f083e2c5dc2a8d9fefe4fc50f2fe73e186aae49/m300_toolbox/files/getfilecount.py#L8) causing the trouble. Judging from your log from `httputil.py:51`, the format looked good and doesn't need any fixing. I think the fix would do something like: try parse the string, if it works, return success. If it doesn't work, try fix it and then parse it. If all fixes are exhausted, return error.
> 
> At the same time, I noticed A500S+ has 9 types of file counts? I need to double check the logic related to [this](https://github.com/XuZhen86/70MaiM300Toolbox/blob/9f083e2c5dc2a8d9fefe4fc50f2fe73e186aae49/m300_toolbox/files/filetype.py#L5) to see if it's compatible with 9 types of file counts because it only lists 5. I think the command line arg could be improved to allow any number of types of files.
> 

It is possible, since the device handles two streams (front/back) and has Event/Normal/Parking for both streams I guess and the front stream for Lapse and Photo. Not sure about the remaining two, 

> For changing other settings, do you think it's useful to add a "Power User" mode, where the user could specify any cgi URL and args, and the tool would just call that URL with the timestamp and sign key. My rationale would be, with fixing the JSON parse error and adding support to unrestricted file types, this tool is no longer limited to M300. Adding a "Power User" mode opens up all the possibilities for customized interactions with many more camera models.

I believe that would be very useful, though I couldn't find out much besides trying out example calls with googling.

In the meantime, I completed what I wanted to achieve, to transfer all files from the DVR to somewhere else and stop/start recording and all the control of this integrated to Home Assistant without the 70mai app, and I'm using your tool to stop/start recording and also to push the SD card allocation to an mqtt sensor. If the power user mode would be implemented I'd go and see what else can be pulled periodically.

The A500S+ has an FTP server enabled (and telnet also works with root and empty password) so it seemed reasonable to just put together some scripts to mirror the sd card contents to another device with lftp over the Xiaomi WiFi AP just after stopping recording.

**Comment by XuZhen86** [comment]
Hi, sorry for taking so long. I've added `--send_command` and `--with_params` for sending arbitrary commands. Please see https://github.com/XuZhen86/70MaiM300Toolbox#sending-commands-manually for examples!

**Comment by danielszilagyi** [comment]
> Hi, sorry for taking so long. I've added `--send_command` and `--with_params` for sending arbitrary commands. Please see https://github.com/XuZhen86/70MaiM300Toolbox#sending-commands-manually for examples!

Hi,

It took some time while I could get back to you, had to re-pair the A500 with my phone today to grab some recordings quickly and this device only supports one paired device, so tried the new method and it fails unfortunately.

```bash
goodman@raspberrypi4:~$ docker run --init --mount type=bind,src=/etc/localtime,dst=/etc/localtime,ro --mount type=bind,src=/home/goodman/dashcam,dst=/mnt --name 70mai-m300-toolbox --rm --workdir /mnt 70mai-m300-toolbox --alsologtostderr --token=67564276aacf1001ad14200a2fc6c796 --generate_token
Traceback (most recent call last):
  File "/usr/local/bin/70mai-m300-toolbox", line 8, in <module>
    sys.exit(app_run_main())
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/m300_toolbox/main.py", line 7, in app_run_main
    app.run(main)
  File "/usr/local/lib/python3.12/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.12/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/m300_toolbox/main.py", line 12, in main
    action._execute_and_print()
  File "/usr/local/lib/python3.12/site-packages/m300_toolbox/actions/action.py", line 26, in _execute_and_print
    return_value = cls.execute(cls.FLAG.value)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/m300_toolbox/actions/generatetoken.py", line 29, in execute
    cls._step_2(timestamp)
  File "/usr/local/lib/python3.12/site-packages/m300_toolbox/actions/generatetoken.py", line 82, in _step_2
    result = Http.extract_result(text_response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/m300_toolbox/http/http.py", line 117, in extract_result
    cls.TEXT_RESPONSE_VALIDATOR.validate(json_response)
  File "/usr/local/lib/python3.12/site-packages/jsonschema/validators.py", line 435, in validate
    raise error
jsonschema.exceptions.ValidationError: '-6674' does not match '^0$'

Failed validating 'pattern' in schema['properties']['ResultCode']:
    {'$comment': 'Ensures the entire ResultCode string equals "0".',
     'pattern': '^0$',
     'type': 'string'}

On instance['ResultCode']:
    '-6674'
command='UserconfirmByBanya.cgi'
params={'-timestamp': '1705512694', '-signkey': '2f57cb1b4bd4cef44750edc0bd774722'}
```

The pairing screen on the device appears and it's approved. The main screen comes back after a while, but when pairing with the mobile app it is different and the led color states change. So I think there might be a difference in the pairing process?

When trying to connect with the supplied token, I get this:

```bash
goodman@raspberrypi4:~$ docker run --init --mount type=bind,src=/etc/localtime,dst=/etc/localtime,ro --mount type=bind,src=/home/goodman/dashcam,dst=/mnt --name 70mai-m300-toolbox --rm --workdir /mnt 70mai-m300-toolbox --alsologtostderr --token=2f57cb1b4bd4cef44750edc0bd774722 --verbosity=4 --get_sd_card_status
I0118 00:37:29.044987 281473673289760 connectionpool.py:244] Starting new HTTP connection (1): 192.168.0.1:80
I0118 00:37:29.072878 281473673289760 connectionpool.py:546] http://192.168.0.1:80 "GET /cgi-bin/getsdstate.cgi?-timestamp=1705534649&-signkey=af166c504085d82ccd89e847fa58f50c HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/local/bin/70mai-m300-toolbox", line 8, in <module>
    sys.exit(app_run_main())
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/m300_toolbox/main.py", line 7, in app_run_main
    app.run(main)
  File "/usr/local/lib/python3.12/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.12/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/m300_toolbox/main.py", line 12, in main
    action._execute_and_print()
  File "/usr/local/lib/python3.12/site-packages/m300_toolbox/actions/action.py", line 26, in _execute_and_print
    return_value = cls.execute(cls.FLAG.value)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/m300_toolbox/actions/getsdcardstatus.py", line 65, in execute
    result = Http.get('getsdstate.cgi')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/m300_toolbox/http/http.py", line 49, in get
    return cls.extract_result(text_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/m300_toolbox/http/http.py", line 117, in extract_result
    cls.TEXT_RESPONSE_VALIDATOR.validate(json_response)
  File "/usr/local/lib/python3.12/site-packages/jsonschema/validators.py", line 435, in validate
    raise error
jsonschema.exceptions.ValidationError: '-6677' does not match '^0$'

Failed validating 'pattern' in schema['properties']['ResultCode']:
    {'$comment': 'Ensures the entire ResultCode string equals "0".',
     'pattern': '^0$',
     'type': 'string'}

On instance['ResultCode']:
    '-6677'
```

The response is only this for the request: `{"ResultCode":"-6677"}`

The 70mai app offered a new firmware, I'm currently on `v1.22.22ww.2023.07.07`
Should I update to the newer firmware?

**Comment by danielszilagyi** [comment]
> Hi, sorry for taking so long. I've added `--send_command` and `--with_params` for sending arbitrary commands. Please see https://github.com/XuZhen86/70MaiM300Toolbox#sending-commands-manually for examples!

Hi,

Sorry for the delete and re-comment but I kept editing for some time and it is better to post this way.
It took some time while I could get back to you, had to re-pair the A500 with my phone today to grab some recordings quickly and had issues with the old token after this, so tried the new method of pairing and it fails unfortunately. I could get over it with the old method though.

The pairing screen on the device appears and it's approved, but only the main screen comes back after a while, when pairing with the mobile app it is different, shows some message on the screen and the led color states change.

I could pair using the old method, I have a pcap file if you are interested let me know how it can get to you.
But I also have some findings based on this pcap.
When the pairing process starts, the client pairs with this very first request:

```json
GET /cgi-bin/BindByBanya.cgi?&-usr=1234567&-signkey=70813fec894e2bf235684ac29e36e308 HTTP/1.1
_os_: Android
_ver_: 3.5.4
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Wed, 17 Jan 2024 17:52:10 GMT
Last-Modified: Wed, 17 Jan 2024 17:52:10 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"0","Result":{"Token":"fc27908a13df6d7069c9a9607d3e2036","timestamp":"1705513930"}}
```

There is a user id in the request, probably stores the key in the user's cloud account. I changed it to 1234567.

Then it sends this "older method" pairing request 4 times:

```json
GET /cgi-bin/UserconfirmByBanya.cgi?&-timestamp=1705513930&-signkey=7b44ed3951665296f983b28e12e97ffb HTTP/1.1
_os_: Android
_ver_: 3.5.4
_product_: 70mai
Host: 192.168.0.1
Connection: Keep-Alive
User-Agent: volley/0

HTTP/1.1 200 OK
Server: thttpd/2.29 23May2018
Content-Type: text/plain; charset=UTF-8
Date: Wed, 17 Jan 2024 17:52:10 GMT
Last-Modified: Wed, 17 Jan 2024 17:52:10 GMT
Accept-Ranges: bytes
Connection: close

{"ResultCode":"-6674"}
```

The app sends this same request the 5th time, everything is same including timestamp and for this 5th time the response looks like this:

`{"ResultCode":"0"}`

The next request is already the get device attributes call.

I removed the quote of the error during pairing with the new method from the comment because it contained mostly python errors not able to parse -6674 as json.

**Comment by XuZhen86** [comment]
Interesting... 
For M300, the call to `UserconfirmByBanya.cgi` gets stuck until the user pushes the button. 
Based on your description, sounds like the call is returned immediately with `{"ResultCode":"-6674"}` until the user pushes the button. The app keeps calling until a `{"ResultCode":"0"}` is returned. 

The "not able to parse -6674 as json" you are seeing should be because the code checks if the ResultCode == 0 before proceeding, and it's stuck at that step because the ResultCode == -6674

I've updated the code, please pull and let me know if it works!

**Comment by wgegh** [comment]
> Adding some input from the packet capture while trying to use all functions in the app: Bootmusic would be especially nice if you could help me try set to 0, since this cannot be done from the app or the device and a bit of annoying even with lowest volume.

Slightly off-topic, but since I found this really interesting project looking for a solution to the same problem:
Open a terminal connection to 192.168.0.1 on port 23, login user 'root' no password, then enter 
 
 `mv -v /mnt/app/res/voice/public/bootsound.raw /mnt/app/res/voice/public/bootsound_1.raw`
(All in one line)

disabled the startup sound on this 70mai dashcam by renaming the soundfile. 
Setting volume to „off“ didn’t help on my device.
